kind: ContinuousQuery
apiVersion: v1
name: wishlist-updates
spec:
  mode: query
  queryLanguage: Cypher
  sources:
    subscriptions:
      - id: wishlist-eh
        nodes:
          - sourceLabel: WishlistItem
  query: >
    MATCH (w:WishlistItem)
    RETURN w.id AS id, w.childId AS childId, w.text AS text, 
           w.category AS category, w.budgetEstimate AS budgetEstimate,
           w.createdAt AS createdAt, w.dedupeKey AS dedupeKey, w.type AS type
