kind: ContinuousQuery
apiVersion: v1
name: test-pipe-format
spec:
  mode: query
  queryLanguage: Cypher
  sources:
    subscriptions:
      - id: wishlist-eh
        nodes:
          - sourceLabel: WishlistItem
  query: |
    MATCH (w:WishlistItem)
    WITH w.text AS suggestion,
         collect(distinct w.childId) AS children
    WITH suggestion, children, size(children) AS freq
    WHERE freq > 0
    RETURN suggestion, freq, children
