kind: ContinuousQuery
apiVersion: v1
name: wishlist-duplicates-by-child
spec:
  mode: query
  queryLanguage: Cypher
  sources:
    subscriptions:
      - id: wishlist-eh
        nodes:
          - sourceLabel: WishlistItem
  view:
    enabled: true
    retentionPolicy: latest
  query: >
    MATCH (w:WishlistItem)
    WITH w.childId AS childId, w.text AS item, count(w) AS duplicateCount
    WHERE duplicateCount > 1
    RETURN childId, item, duplicateCount
