kind: ContinuousQuery
apiVersion: v1
name: wishlist-inactive-children-3d
spec:
  mode: query
  queryLanguage: Cypher
  sources:
    subscriptions:
      - id: wishlist-eh
        nodes:
          - sourceLabel: WishlistItem
  view:
    enabled: true
    retentionPolicy: latest
  query: >
    MATCH (w:WishlistItem)
    WITH w.childId AS childId, max(drasi.changeDateTime(w)) AS lastEvent
    WHERE lastEvent <= datetime.realtime() - duration({ days: 3 })
    RETURN childId, lastEvent
