kind: ContinuousQuery
apiVersion: v1
name: wishlist-duplicates-global
spec:
  mode: query
  queryLanguage: Cypher
  sources:
    subscriptions:
      - id: wishlist-eh
        nodes:
          - sourceLabel: WishlistItem
  view:
    enabled: true
    retentionPolicy: latest
  query: |
    MATCH (w:WishlistItem)
    RETURN w.text AS item, count(w) AS itemCount
