kind: QueryContainer
apiVersion: v1
name: default
spec:
  defaultStore: redis
  queryHostCount: 1
  results:
    MONGO_RESULT_STORE_COLL_NAME: Results
    MONGO_RESULT_STORE_DB_NAME: Drasi
    MONGO_URI: mongodb://drasi-mongo:27017
  storage:
    memory:
      enableArchive: false
      kind: memory
    redis:
      connectionString: redis://drasi-redis:6379
      kind: redis
