kind: Reaction
apiVersion: v1
name: wishlist-debug
spec:
  kind: Debug
  queries:
    wishlist-updates:
    wishlist-trending-1h:
    wishlist-duplicates-by-child:
    wishlist-inactive-children-3d:
---
kind: Reaction
apiVersion: v1
name: wishlist-signalr
spec:
  kind: SignalR
  queries:
    wishlist-updates:
    wishlist-trending-1h:
    wishlist-duplicates-by-child:
    wishlist-inactive-children-3d:
---
kind: Reaction
apiVersion: v1
name: wishlist-sync-cosmos
spec:
  kind: SyncDaprStateStore
  queries:
    wishlist-updates: '{"stateStoreName":"cosmos-state","keyField":"childId"}'
