kind: Source
apiVersion: v1
name: wishlist-eh
spec:
  kind: EventHub
  identity:
    kind: MicrosoftEntraWorkloadID
    clientId: ${DRASI_MI_CLIENT_ID}
  properties:
    host: ${EVENTHUB_FQDN}
    eventHubs:
      - wishlist-events
    bootstrapWindow: 7200
  middleware:
    - kind: map
      name: wishlist-mapper
      wishlist-events:
        insert:
          - selector: $
            op: Insert
            label: WishlistItem
            id: $.id
            properties:
              id: $.id
              childId: $.childId
              text: $.text
              category: $.category
              budgetEstimate: $.budgetEstimate
              createdAt: $.createdAt
              dedupeKey: $.dedupeKey
              type: $.type
